title: COVID19
author: Kristin

description: > # this means to ignore newlines until "baseurl:"
Trying to figure out how to build new data connections and pull more data to create meaningful analyses

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
